<BlockSwitcher>

<Block name="Async/Await">

```swift
func signIn(username: String) async {
    do {
        let signInResult = try await Amplify.Auth.signIn(username: username)
        if case .confirmSignInWithCustomChallenge(_) = signInResult.nextStep {
            // Ask the user to enter the custom challenge.
        } else {
            print("Sign in succeeded")   
        }       
    } catch let error as AuthError {
        print("Sign in failed \(error)")
    } catch {
        print("Unexpected error: \(error)")
    }
}
```

</Block>

<Block name="Combine">

```swift
func signIn(username: String, password: String) -> AnyCancellable {
    Amplify.Publisher.create {
        try await Amplify.Auth.signIn(username: username)
        }.sink {
            if case let .failure(authError) = $0 {
                print("Sign in failed \(authError)")
            }
        }
        receiveValue: { result in
            if case .confirmSignInWithCustomChallenge(_) = result.nextStep {
                // Ask the user to enter the custom challenge.
            } else {
                print("Sign in succeeded")
            }
        }
}
```

</Block>

</BlockSwitcher>

Since this is a custom authentication flow with a challenge, the result of the signin process has a next step `.confirmSignInWithCustomChallenge`. Implement a UI to allow the user to enter the custom challenge.