If the next step is `CONFIRM_SIGN_IN_WITH_SMS_MFA_CODE`, Amplify Auth has sent the user a random code over SMS, and is waiting to find out if the user successfully received it. To handle this step, your app's UI must prompt the user to enter the code. After the user enters the code, your implementation must pass the value to Amplify Auth `confirmSignIn` API.

Note: the signIn result also includes an `AuthCodeDeliveryDetails` member. It includes additional information about the code delivery such as the partial phone number of the SMS recipient.

<BlockSwitcher>

<Block name="Java">

```java
try {
      Amplify.Auth.confirmSignIn(
            "confirmation code",
            result -> {
                if (result.isSignedIn()) {
                    Log.i(TAG, "Confirm signIn succeeded");
                } else {
                    Log.i(TAG, "Confirm sign in not complete. There might be additional steps: " + result.getNextStep());
                    // Switch on the next step to take appropriate actions.
                    // If `signInResult.isSignedIn` is true, the next step
                    // is 'done', and the user is now signed in.
                }
            },
            error -> Log.e(TAG, "Confirm sign in failed: " + error)
<<<<<<< Updated upstream
    );
      } catch (Exception error) {
          Log.e(TAG, "Unexpected error: "+error);
      }
=======
            );
} catch (Exception error) {
    Log.e(TAG, "Unexpected error: "+error);
}
>>>>>>> Stashed changes
```
</Block>

<Block name="Kotlin">

```kotlin
try {
    Amplify.Auth.confirmSignIn(
          "confirmation code",
          { result ->
              if (result.isSignedIn) {
                  Log.i(TAG,"Confirm signIn succeeded")
              } else {
                  Log.i(TAG, "Confirm sign in not complete. There might be additional steps: ${result.nextStep}")
                  // Switch on the next step to take appropriate actions.
                  // If `signInResult.isSignedIn` is true, the next step
                  // is 'done', and the user is now signed in.
              }
          }
    ) { error -> Log.e(TAG, "Confirm sign in failed: $error")}
} catch (error: Exception) {
    Log.e(TAG, "Unexpected error: $error")
}
```
</Block>

</BlockSwitcher>
