```swift
do {
    try await Amplify.DataStore.stop()
    print("DataStore stopped")
} catch let error as DataStoreError {
    print("Error stopping DataStore: \(error)")
} catch {
    print("Unexpected error \(error)")
}

```